### ISSUE TITLE
Should not complain about missing server if you yaml contains only components

### ISSUE THREAD

**Issue by cvgaviao** [Redocly/redocly-vs-code#57] opened 2023-11-29 06:19 UTC
**What happened?**
I'm getting an error mark in an yaml containing only components

**What should have happened instead?**
The missing server rule must be applied only when paths (or webhook?) are present.

Also, I'm getting `never used` warnings for all schemas in this case.

**Minimal reproducible OpenAPI snippet**
```
openapi: 3.1.0
info: 
  title: Common Schemas
  version: "latest"

components: 
  schemas: 
    BusinessUnit:
      title: BusinessUnit
      type: object
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
```

*If possible, include a short example of your OpenAPI definition that we can use to simulate the problem.*

**Screenshots**
![image](https://github.com/Redocly/redocly-vs-code/assets/251734/d4513c8a-2e00-4a50-a8d1-058392cae0a8)

**Additional context**

Release 0.3.3 (2023-11-16)

**Comment by lornajane** [comment] 2023-11-29 09:36
I think this is related to (if not exactly a duplicate) #51

**Comment by tatomyr** [comment] 2023-11-29 17:06
This is not an extension issue. The behaviour of the Redocly CLI linter will be the same. Could you provide a link to the specification to clarify the correct behaviour?

> Also, I'm getting never used warnings for all schemas in this case.

They are unused indeed 🙂. You can turn off warnings or make any other adjustments to rules using Redocly config: https://redocly.com/docs/cli/configuration/rules/#configure-your-linting-rules

**Comment by adamaltman** [comment] 2023-12-22 00:58
I don't think this is a bug.

Our default rules are (mildly) opinionated, and if you don't supply a `redocly.yaml` to turn off the server or unused components rules you will see errors or warnings.

You can control with a configuration file.

Please re-open if you think I'm incorrectly closing this as "not a bug"...

**Closed by adamaltman** 2023-12-22 00:58 UTC
Labels: Type: Bug
